# Generated by Django 2.1.7 on 2019-03-12 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mod_aims_lo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='mod_AM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('proportion_mark', models.IntegerField(default=0)),
                ('num_of_hour', models.IntegerField(default=0)),
                ('word_length', models.IntegerField(default=0)),
                ('written', models.IntegerField(default=0)),
                ('course_work', models.IntegerField(default=0)),
                ('practical', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='mod_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('depart', models.CharField(max_length=32)),
                ('institution', models.CharField(default='Sheffield', max_length=32)),
                ('email', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='mod_requisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre', models.CharField(max_length=32)),
                ('co', models.CharField(max_length=32)),
                ('excluded', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='mod_TLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('actual_hour', models.IntegerField(default=0)),
                ('scheduled_hour_num', models.IntegerField(default=0)),
                ('scheduled_hour_perc', models.IntegerField(default=0)),
                ('placement_hour_num', models.IntegerField(default=0)),
                ('placement_hour_perc', models.IntegerField(default=0)),
                ('independ_hour_num', models.IntegerField(default=0)),
                ('independ_hour_perc', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='mod_TM_AM_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('link', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='module_info',
            fields=[
                ('mod_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('smester_taught', models.CharField(max_length=32)),
                ('smester_asses', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=64)),
                ('date', models.CharField(max_length=64)),
                ('credit', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('special_restriction', models.CharField(max_length=128)),
                ('qualification', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='mod_tm_am_links',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_web.module_info'),
        ),
        migrations.AddField(
            model_name='mod_tlm',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_web.module_info'),
        ),
        migrations.AddField(
            model_name='mod_requisites',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_web.module_info'),
        ),
        migrations.AddField(
            model_name='mod_contact',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_web.module_info'),
        ),
        migrations.AddField(
            model_name='mod_am',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_web.module_info'),
        ),
        migrations.AddField(
            model_name='mod_aims_lo',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_web.module_info'),
        ),
    ]
