# Generated by Django 2.1.7 on 2019-03-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Aims',
            },
        ),
        migrations.CreateModel(
            name='Learnoutcomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_outcomes', models.TextField(default='')),
                ('aims', models.ForeignKey(null=True, on_delete=False, to='my_web.Aims')),
            ],
            options={
                'verbose_name_plural': 'Learning outcomes',
            },
        ),
        migrations.CreateModel(
            name='Program_cont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program_title', models.CharField(max_length=32)),
                ('Program_code', models.CharField(max_length=32)),
                ('JACS_Code', models.CharField(max_length=32)),
                ('Level_of_study', models.CharField(max_length=32)),
                ('Final_Qualification', models.CharField(max_length=32)),
                ('QAA_FHEQ_Level', models.CharField(max_length=32)),
                ('Intermediate_Qualification', models.CharField(max_length=120)),
                ('Teaching_Institution', models.CharField(max_length=32)),
                ('Faculty', models.CharField(max_length=32)),
                ('Department', models.CharField(max_length=32)),
                ('Other_Department_involved_in_teaching_the_programm', models.CharField(max_length=32)),
                ('Mode_of_Attendnce', models.CharField(max_length=32)),
                ('Duration_of_the_Programme', models.CharField(max_length=32)),
                ('Date_of_production', models.CharField(max_length=32)),
                ('Accrediting_Professional_or_Statutory_Body', models.CharField(max_length=32)),
                ('Background_to_the_programme_and_subject_area', models.TextField(default='')),
                ('Teaching_learning_and_assessment', models.TextField(default='')),
                ('aims1', models.ForeignKey(null=True, on_delete=False, to='my_web.Aims')),
                ('aims2', models.ForeignKey(null=True, on_delete=False, related_name='topic_content_type', to='my_web.Aims')),
                ('aims3', models.ForeignKey(null=True, on_delete=False, related_name='topic_content_typ', to='my_web.Aims')),
                ('aims4', models.ForeignKey(null=True, on_delete=False, related_name='topic_content_ty', to='my_web.Aims')),
                ('aims5', models.ForeignKey(null=True, on_delete=False, related_name='topic_content_t', to='my_web.Aims')),
                ('l_outcomes1', models.ForeignKey(null=True, on_delete=False, to='my_web.Learnoutcomes')),
                ('l_outcomes2', models.ForeignKey(null=True, on_delete=False, related_name='topic_con', to='my_web.Learnoutcomes')),
                ('l_outcomes3', models.ForeignKey(null=True, on_delete=False, related_name='topic_content', to='my_web.Learnoutcomes')),
                ('l_outcomes4', models.ForeignKey(null=True, on_delete=False, related_name='topic_conten', to='my_web.Learnoutcomes')),
                ('l_outcomes5', models.ForeignKey(null=True, on_delete=False, related_name='topic_conte', to='my_web.Learnoutcomes')),
            ],
            options={
                'verbose_name_plural': 'Program contents',
            },
        ),
    ]
